### model
model_name_or_path: /mnt/default/finetuned-model/llama3.1-8b-full-sft-AutoIF_instruct_61k/checkpoint-1000 # /mnt/default/finetuned-model/llama3.1-8b-full-sft-lima/checkpoint-200

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json
pref_beta: 0.3 # 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: autoif_dpo_pairs
template: llama3
cutoff_len: 4096 # 2048 # 1024
# max_samples: 1000
# overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/default/finetuned-model/llama3.1-8b-full-dpo-autoif_dpo_pairs-AutoIF_instruct_61k_ckpt1000
logging_steps: 1
save_steps: 50 # 100
save_only_model: true
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1 # 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-7 # 5.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
report_to: wandb
run_name: llama-factory-dpo-full-autoif_dpo_pairs-AutoIF_instruct_61k_ckpt1000 # optional

### eval
val_size: 0.05 # 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50 # 150
